coco_classes = {
    "Person": 0,
    "Bicycle": 1,
    "Car": 2,
    "Motorcycle": 3,
    "Airplane": 4,
    "Bus": 5,
    "Train": 6,
    "Truck": 7,
    "Boat": 8,
    "Traffic Light": 9,
    "Fire Hydrant": 10,
    "Stop Sign": 11,
    "Parking Meter": 12,
    "Bench": 13,
    "Bird": 14,
    "Cat": 15,
    "Dog": 16,
    "Horse": 17,
    "Sheep": 18,
    "Cow": 19,
    "Elephant": 20,
    "Bear": 21,
    "Zebra": 22,
    "Giraffe": 23,
    "Backpack": 24,
    "Umbrella": 25,
    "Handbag": 26,
    "Tie": 27,
    "Suitcase": 28,
    "Frisbee": 29,
    "Skis": 30,
    "Snowboard": 31,
    "Sports Ball": 32,
    "Kite": 33,
    "Baseball Bat": 34,
    "Baseball Glove": 35,
    "Skateboard": 36,
    "Surfboard": 37,
    "Tennis Racket": 38,
    "Bottle": 39,
    "Wine Glass": 40,
    "Cup": 41,
    "Fork": 42,
    "Knife": 43,
    "Spoon": 44,
    "Bowl": 45,
    "Banana": 46,
    "Apple": 47,
    "Sandwich": 48,
    "Orange": 49,
    "Broccoli": 50,
    "Carrot": 51,
    "Hot Dog": 52,
    "Pizza": 53,
    "Donut": 54,
    "Cake": 55,
    "Chair": 56,
    "Couch": 57,
    "Potted Plant": 58,
    "Bed": 59,
    "Dining Table": 60,
    "Toilet": 61,
    "TV": 62,
    "Laptop": 63,
    "Mouse": 64,
    "Remote": 65,
    "Keyboard": 66,
    "Cell Phone": 67,
    "Microwave": 68,
    "Oven": 69,
    "Toaster": 70,
    "Sink": 71,
    "Refrigerator": 72,
    "Book": 73,
    "Clock": 74,
    "Vase": 75,
    "Scissors": 76,
    "Teddy Bear": 77,
    "Hair Dryer": 78,
    "Toothbrush": 79
}